### ISSUE TITLE
[Bug]When export a node sandbox container to github goes wrong

### ISSUE THREAD

**Issue by ThatToti** [CompuIves/codesandbox-client#1130]
# 🐛 bug report

## Description of the problem
When i export a node sandbox container to Github.The template type should be `node`.But it changes to `create-react-app`

## How has this issue affected you? What are you trying to accomplish?
I want to write some demos on `node` template and link the code to Github.But it seems like that it couldn't work well at this beta version.

> Before the export
![image](https://user-images.githubusercontent.com/17880183/46255635-e5f44500-c4d1-11e8-800c-2b0e00068ff3.png)

> After the export 
![image](https://user-images.githubusercontent.com/17880183/46255619-bba28780-c4d1-11e8-86e4-71dddaafcf17.png)

###  Link to sandbox: [link]() (optional)
[The node demo](https://codesandbox.io/s/2xm6qzmyyr)

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | PROD-1538077445-546871f|
| Browser | chrome v69|
| Operating System | mac os 10.13.2|

**Comment by dwuster** [comment]
The [tutorial](https://codesandbox.io/docs/importing#import-from-github) say to use `{ "template":"node" }` in `./sandbox.config.json`

`codesandbox-importers/packages/types/index.d.ts` -> [ITemplate](https://github.com/codesandbox-app/codesandbox-importers/blob/master/packages/types/index.d.ts#L24)
don't have "node" option.

**Comment by ThatToti** [comment]
thanks!

It seems like the problem is solved.So,I close this issue.

**Comment by dwuster** [comment]
It's not solved, I have the same problem with "node" template
