### ISSUE TITLE
"request entity too large" error when trying to export to GitHub

### ISSUE THREAD

**Issue by durkinio** [CompuIves/codesandbox-client#1430]
# 🐛 bug report

## Description of the problem
When I create sandbox using this Gatsby starter (https://github.com/netlify-templates/gatsby-starter-netlify-cms), fork it, and try to export to GitHub (using the "create repository" button), the export fails with a "request entity too large" error.

![screenshot 2019-01-06 at 10 34 31 pm](https://user-images.githubusercontent.com/24935891/50742480-c45ad600-1203-11e9-9a75-e0dc2787efc0.png)

## How has this issue affected you? What are you trying to accomplish?
I can't export the sandbox to GitHub.

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | PROD-1546812717-fd56384b
| Browser | Google Chrome OS/Version 70.0.3538.110 (Official Build) (64-bit)
| Operating System | Google Chrome OS/Version 70.0.3538.110 (Official Build) (64-bit)

**Comment by Chuckame** [comment]
Same as you !

**Comment by looeee** [comment]
I'm also encountering this error, when forking an existing repo. 

Here's the original:
https://codesandbox.io/s/github/looeee/discoverthree.com-examples/tree/master/4-materials/1b-material-base-class-occlusion

And here's the forked version:
https://codesandbox.io/s/pm35jk3z8q

If I click on the GitHub tab, this "request entity too large" error pops up, and the words "Fetching changes..." stay there forever.

**Comment by CompuIves** [comment]
Interesting, I got the same error just now. I'll check which service is returning this error.

**Comment by durkinio** [comment]
Looks like this is resolved 💯  Closing this out.

**Comment by looeee** [comment]
I've just tested this and I'm still getting the same error. Can you please reopen? 

I've updated the links above so you can test with link from my previous comment.
