### ISSUE TITLE
Emmet in HTML files

### ISSUE THREAD

**Issue by danekt** [CompuIves/codesandbox-client#1476]
# 🐛 bug report

### My Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | codesandbox.io
| Browser | Google Chrome 71.0.3578.98, Safari 12.0.2, Firefox 64.0.2
| Operating System | MacOS 10.13.6

**Comment by SaraVieira** [comment]
Just updating that it's still an issue

**Comment by cespedesj** [comment]
For me the issue persists :cry:

**Comment by SaraVieira** [comment]
Yeh, still an issue and it will be fixed in the next release of VSCode

Those issues were closed as duplicates :(

**Comment by SaraVieira** [comment]
Fixed in the latest release of VSCode 🎉

**Comment by etunka** [comment]
Emmet still doesn't work for me in html files for `PROD-1566292503-c18c081c8` . Tried in latest versions of Chrome (also incognito) and Safari. It seems to be working for my colleagues with same product id.

**Comment by afminmax** [comment]
FYI to those stumped with auto complete failures and land here, to enable autocompletion in Codesandbox, go to VS Code Settings and search for "Auto closing" - You will be presented with a list of options for different editors and extensions. Choose what you need.

**Comment by frankieali** [comment]
I've noticed that the Emmet suggestions only appear on every other keystroke after you get past the tag name. For instance `div.modal` once I begin typing the class name, emmet suggestions only appear on every other keystroke. Also, the emmet suggestion disappears completely if there is a `wordBasedSuggestions` match.
