### ISSUE TITLE
ReactIs.isMemo is not a function

### ISSUE THREAD

**Issue by eps1lon** [CompuIves/codesandbox-client#1521]
# 🐛 bug report

## Description of the problem
The version of `react-is` that is used by `hoist-non-react-statics` does not match the version defined in its package.json.

This does not happen when built locally with `yarn@1.12.0`. I suspect the `node_modules/` layout created by the client is wrong. There is probably another dependency on `react-is` from another package that does not semver match the version required from `hoist-non-react-statics`.

## How has this issue affected you? What are you trying to accomplish?
Running the linked sandbox.

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | PROD-1549276057-35219357
| Browser | Chrome Version 72.0.3626.81 (Official Build) (64-bit)
| Operating System | Ubuntu 18.04.1 LTS

**Comment by erichodges** [comment]
I'm having the same problem!

**Comment by davidalekna** [comment]
Same here!

**Comment by ShimiSun** [comment]
workaround suggestions anyone?

**Comment by CompuIves** [comment]
Looking at it now. This is the information of `react-is` in the sandbox:

```
resolved: "16.7.0"
semver: "^16.6.3"
```

So this means that the requested version by `hoist-non-react-statics` is `^16.6.3`, and the resolved version is `16.7.0`, which is correct. `isMemo` got added in `16.8.1`.

So I believe that what we're doing is correct, but we have a different (but compatible) result compared to `yarn`.

Another fix outside of CodeSandbox would be for `hoist-non-react-statics` to pin `react-is` to `~16.8.1`.

I can take a closer look tomorrow and figure out if we can have a closer result to `yarn` so we can fix it on our side.

**Comment by eps1lon** [comment]
> `isMemo` got added in `16.8.1`

Where did you get that information? It was in the code in [`16.7.0`](https://github.com/facebook/react/blob/v16.7.0/packages/react-is/src/ReactIs.js) and it was published in 16.7: https://www.npmjs.com/package/react-is/v/16.7.0https://www.npmjs.com/package/react-is/v/16.7.0

[`hoist-non-react-static` is declaring 16.7 as a direct dependency](https://github.com/mridgway/hoist-non-react-statics/blob/v3.3.0/package.json)

>So I believe that what we're doing is correct, but we have a different (but compatible) result compared to `yarn`.

`yarn` is causing no error. So while you are right that it is (obviously) different it is not compatible.

**Comment by CompuIves** [comment]
Ahh, you're right. Thanks for correcting me!

So what I'm seeing is that we got the wrong semver for `react-is`. `@material-ui/utils` specifies it needs `^16.6.3` while `hoist-non-react-static` in `@material-ui/core` specifies it needs `^16.7.0`. We took priority with `^16.6.3` while we should've used `^16.7.0`.

I'll check the code that merges these dependencies.

**Comment by CompuIves** [comment]
I found the problem and I'm deploying a fix now. The problem was related to replacing the file contents with the correct version (I think @eps1lon was already on to this). I fixed it with this commit https://github.com/codesandbox/dependency-packager/commit/a82f30de8eaf5213b38a72f1e9d25785547a6ec6.

Purging the cache will be challenging, I'm going to try something.

**Comment by CompuIves** [comment]
It seems to be working when adding a new dependency to generate a new cache: https://codesandbox.io/s/13jx2l8qz4

**Comment by jay-jlm** [comment]
I have been applying for jobs by sharing Codesandbox links as portfolio for the past few days.
I was wondering why I was not getting any responses until some kind soul alerted my those links were not working.
Hope this gets fixed soon but the damage for me has already been done.  😕

**Comment by CompuIves** [comment]
I'm sorry that that happened to you. The error is already fixed, you may have to refresh twice to force the service worker to download a new version.

**Comment by jay-jlm** [comment]
I tried on anonymous tab mode in 2 different browsers and still get the same error, even after refreshing multiple times.
https://j2q2m37n2w.codesandbox.io/

**Comment by erichodges** [comment]
You might try a hard reload, If you're on chrome/firefox then it's cmd + shift + R.

**Comment by CompuIves** [comment]
Hmm, seems like the CDN hasn't finished invalidating the cache yet. It should be propagated soon to all sandboxes.

**Comment by CompuIves** [comment]
To make it work immediately you could upgrade a dependency, like `react`, to a newer version. That will force the bundler to generate a new dependency bundle.

**Comment by oliviertassinari** [comment]
I had to add `"hoist-non-react-statics": "3.3.0",` in the dependencies to make it work. Clearing my service workers didn't help.
