### ISSUE TITLE
All Aurelia TypeScript Sandboxes Broken with Latest CodeSandbox

### ISSUE THREAD

**Issue by EisenbergEffect** [CompuIves/codesandbox-client#1550]
# 🐛 bug report

## Description of the problem

At some recent time, 100% of Aurelia's TS-based CodeSandboxes broke, with no changes on our part. These dozens of sandboxes are embedded throughout or documentation. We now have customers complaining that all of our demos are broken. I have attempted a few things myself to see if I could fix it quickly, but nothing seems to work. Our JS sandboxes work fine, but those aren't the ones used in the documentation, only our home page (thankfully our home page isn't broken). In any case, this is pretty damaging for our community and especially for newcomers to the framework that now encounter broken documentation.

###  Link to sandbox

* https://codesandbox.io/s/zw9zjy0683

The above is our simple, base sandbox on which all the others were built. As far as we know, it's completely broken in all browsers and OSes. This breakage was first reported by our framework customers today while they were using our documentation.

**Comment by CompuIves** [comment]
I'm so sorry for that! I created a fix and added the Aurelia sandbox to our tests to make sure it won't happen again.

Fix should be live within 10 minutes.

**Comment by EisenbergEffect** [comment]
Is it deployed? It seems to still be broken ;(

**Comment by EisenbergEffect** [comment]
I'm getting different errors from before but still things seem broken.

**Comment by EisenbergEffect** [comment]
@CompuIves We need to re-open this because it's not fixed. Please try the link above. Three days of broken docs now is hurting us.

**Comment by SaraVieira** [comment]
Sorry , repeopend

@CompuIves

**Comment by CompuIves** [comment]
Ah I'm so sorry for that! This was another problem, our packager neglected a couple of files. I deployed a fix now, will now purge the caches.

**Comment by EisenbergEffect** [comment]
Let me know when I can test again. I just checked the link above and was still getting an error ;(

**Comment by bigopon** [comment]
@CompuIves @SaraVieira Thanks for working on this. I've tried to analyze the causes of this, and noticed that it seems Aurelia CodeSandbox `Loader` is no longer able to resolve modules in `node_modules` dynamically.

This is due to dynamic nature of Aurelia, where there are some joint modules (eg: templating + binding joint by `aurelia-templating-binding` module) are required when an instance of Aurelia class starts.

I verified my theory by adding something like this to a test sandbox:
```ts
import 'aurelia-templating-binding';
import 'aurelia-templating-router';
```
as you can see from this link https://codesandbox.io/s/x7295pmxqo . It started to work again, as compared to https://codesandbox.io/s/9zvm06x9pp

From that, I would assume that there were some changes from CodeSandbox that blocked/broke the dynamic node_modules requiring usage.

If CodeSandbox team could help resolve it, it would be awesome, as we don't have to iterate through all demos and fix them one by one, as a workaround.

**Comment by CompuIves** [comment]
I added a small cache busting system that allows us to easily cache bust from now on. The mentioned sandboxes should now work, I reset the dependency cache.

I'm sorry for this issue! I'll make sure from now on that our integration tests are done on the production API server.

**Comment by EisenbergEffect** [comment]
Woohoo! Thank you @CompuIves !!! It looks like everything is working again 😄 I know it was probably frustrating, but we appreciate you all working to get this fixed for us.
